### ISSUE TITLE
Allow to run on server

### ISSUE THREAD

**Issue by benoneal** [jsstyles/jss-vendor-prefixer#2]
It would be super useful for isomorphic and static js apps to be able to use this plugin on the server. It seems the best way to do this would be to implement all vendor prefixes when run on the server (like all other css pre-compiler vendor prefixers). This way the initial payload will contain a fully-style page, which can be cached for later requests.

**Comment by kof** [comment]
Or just use autoprefixer on final css, which is even better than generating prefixes for all browsers also it fixes a lot of css.

**Comment by benoneal** [comment]
What if the css is embedded in the <head> of a server-generated markup string though?

**Comment by kof** [comment]
potentially it can run through autoprefixer before it lands in the markup, also its possible to just generate stylesheet files out of it and run them through autoprefixer later.

Best,
Oleg Slobodskoi

https://kof.github.com
