### ISSUE TITLE
Should vendor-prefixer load before the camel-case plugin?

### ISSUE THREAD

**Issue by trusktr** [jsstyles/jss-vendor-prefixer#4]
Just want to double check. I'm currently loading vendor-prefixer, then camel-case.

**Comment by kof** [comment]
thanks for checking, just realized the order in readme is wrong, vendor prefixer expects dasherized syntax and so if camel case is used  camel-case plugin needs to be applied first

**Comment by trusktr** [comment]
Maybe plugins can specify certain plugins that they should run after, if present.

**Comment by kof** [comment]
This would mean plugins know each other and this is bad.

**Comment by kof** [comment]
I don't know a better way than documentation. Middelware serverside can also depend on order.
